### ISSUE TITLE
[PULL REQUEST ISSUE] Mention your issues regarding pull request

### ISSUE THREAD

**Issue by Uyadav207** [ISTESRMNCR/CODE-CAMP-2020#6]
# Announcements Regarding Pull Request 📢

- The Pull request will not be accepted before `19th July, 2020` from `8 AM` to `10 PM`.
- Recommendation to fork repository after `15th July, 2020`.
- Select theme and start making your team folder.

### To see how to make Pull Request Visit 👉 [Here](https://codecamphackathon.netlify.app/makingRegistration/)

**Comment by KaranBengani** [comment]
![pic1](https://user-images.githubusercontent.com/63871616/87657263-38225b00-c778-11ea-8181-cb4c2e0677b7.PNG)

 whose github link goes here?
![pic2](https://user-images.githubusercontent.com/63871616/87657719-d4e4f880-c778-11ea-8dd5-82f0fa0af880.PNG)


the hosted link will be of this code camp repository or do we need to make anew reposiory

**Comment by Uyadav207** [comment]
@KaranBengani , Thanks for raising Issue.

`In GitHub link` : make a blank repository in which u have to push your project for hackathon and mention it in `Github-link` section

`In Hosted-Link` :  This NEED NOT to to be filled for Registrations Pull Request. will consider it for final submssions. For now leave it blank. 
But In this section you need to give the link of the application that u will be building for hackathon.


The Github Link above is your teams github ID link. (ONLY THE LEADER / PERSON SUBMITTING PULL REQUEST)

**Comment by KaranBengani** [comment]
While filling the team details ,  what goes into the Specialization part?

**Comment by Uyadav207** [comment]
@KaranBengani , write about the technology you are good at or always do. 
Example : Python  | MERN Stack Developer | DataScientist | AI Expert etc.

**Comment by Nalin-Angrish** [comment]
In the template, there are few fields like 'Team-Quote' and 'Application type', so what is to be filled in that?

**Comment by Uyadav207** [comment]
@Nalin-2005 , In Team Quotes : Quotation of teams i.e any TAGLINE ... Would go here.
In Application Type : what application you are building.. ( Example : Mobile application , web application, desktop application ) etc..

**Comment by Nalin-Angrish** [comment]
I don't go to any university and am a schoolboy so should i write my school's name in the "University-name" field?

**Comment by raghavg27** [comment]
@Nalin-2005 yes you should mention your school's name

**Comment by KaranBengani** [comment]
at the top of the form there is a description part.......what to fill over there

**Comment by KaranBengani** [comment]
What is difference in the content of technical skills and specialization?

**Comment by Uyadav207** [comment]
@KaranBengani ,
In description section : Description of the team goes here .. ( Example : Some funny or nerdy stuff one like that's upto you. ) 

Technical skills : Is basically `TECH STACK` you will be using in this project...
Specialization : Example- Web Developer  | aspiring data Scientist | Back-end development etc  | MERN STACK specialist .etc..

I hope you got some Idea.

**Comment by Nalin-Angrish** [comment]
if i use jquery along with javascript or flask in python will i have to mention jquery/flask also in my tech-stach?

**Comment by Uyadav207** [comment]
@Nalin-2005 and @KaranBengani , Guys ... Tech Stack is not a big Deal ... If anything Goes wrong.. will tell you to Correct then and there only.. Don't Worry.

Tech Stack is not going to disrupt your registration. SO

![image](https://media2.giphy.com/media/xT5LMX83QTnxQdG70A/200.gif)

**Comment by KaranBengani** [comment]
all members need to join the whatsapp group?

**Comment by Uyadav207** [comment]
@KaranBengani , Yes

**Comment by KaranBengani** [comment]
Can we change our team mate's name if there is any error?

**Comment by Uyadav207** [comment]
> Can we change our team mate's name if there is any error?
> 
> 

Yes,  commit changes and send the pull request. Do it asap... give your commits a title changing files or something

**Comment by KaranBengani** [comment]
I have raised the pull request again....please look into it

**Comment by Uyadav207** [comment]
#44  @KaranBengani , merged

**Comment by KaranBengani** [comment]
thank you

**Comment by s4shantanu** [comment]
How can I register?

**Comment by Uyadav207** [comment]
@s4shantanu , Have you send us your Pull request for registration.

**Comment by Uyadav207** [comment]
@s4shantanu , for registrations please follow these guildines https://github.com/ISTESRMNCR/CODE-CAMP-2020/issues/6#issue-654715629

**Comment by s4shantanu** [comment]
Okay

**Comment by s4shantanu** [comment]
I completed my registration . But I don't know the register is correct.

**Comment by Uyadav207** [comment]
telegram : t.me/utkarshyadav207

DM me here.  @s4shantanu .  ASAP

**Comment by Uyadav207** [comment]
@s4shantanu , You are Going Wrong seen your profile.. DM ME ON TELEGRAM PLS ... ASAP

telegram  :  t.me/utkarshyadav207

**Comment by Uyadav207** [comment]
# Closing this PULL REQUEST QUERY SESSION.

- [x] Registrations Done
