### ISSUE TITLE
Updating github repo link

### ISSUE THREAD

**Issue by avats-dev** [ISTESRMNCR/CODE-CAMP-2020#68]
#### Should I fork and add a PR?

**Comment by avats-dev** [comment]
> ### I have to update my github repo link for the project in registration, so what should I do?
> #### Should I fork and add a PR?

**Team :** "TheGlitch"

**Comment by Uyadav207** [comment]
@avats-dev , No need to resend the PR. Renaming the Github repo to the older name will solve the issue.  The name you used is not occupied by other instantly

**Comment by Uyadav207** [comment]
@avats-dev , Do Ping within this thread if the issue has resolved.

**Comment by avats-dev** [comment]
**I have renamed my repo as before, and so issue is resolved. Thanks @Uyadav207 for the help.**
