### ISSUE TITLE
[HOSTED LINK] Issues raised by Teams

### ISSUE THREAD

**Issue by Amit588986** [ISTESRMNCR/CODE-CAMP-2020#72]
Should we push keystore file along with the apk bundle???

**Comment by Uyadav207** [comment]
@Amit588986, Keystore keeps sensitive data, Avoid pushing it.

- StackOverflow : https://stackoverflow.com/questions/33780137/should-i-commit-release-key-store-for-android-app-to-team-repository  

The Above Link Might Help you...

**Comment by Uyadav207** [comment]
# ISSUES REGARDING HOSTED LINK WILL ALSO GO UNDER THIS THREAD

**Comment by Uyadav207** [comment]
@Amit588986 , Keep this issue open... , Because may someone  have the same query. this might help
